require "rake/testtask"

desc 'Run tests'
task :test do
  sh 'bundle exec ruby ./test/cms_test.rb'
end

desc 'Run server'
task :run do
  sh 'bundle exec ruby cms.rb'
end

=begin 
# Why do this?
desc 'Run tests'
task :default => :test

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.test_files = FileList['test/**/*_test.rb']
end
=end
